### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by vidgit** [TanmayaBhatt/Improved-Ranking-Based-Recommendations-Based-on-Fuzzy-Data-Analysis#1]
TODO:
Add how to use

**Comment by TanmayaBhatt** [comment]
Hi.
This is a tutorial to use libsvm,
https://www.youtube.com/watch?v=gePWtNAQcK8.

As for creating your test files to train in LIBSVM, you can use the codes given in LIBSVM folders or convert your file yourself to create a LIBSVM compatible file.
